# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QGraphicsPixmapItem
from PyQt5.QtWidgets import QGraphicsScene

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnBaseline = QtWidgets.QPushButton(self.centralwidget)
        self.btnBaseline.setGeometry(QtCore.QRect(200, 620, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnBaseline.setFont(font)
        self.btnBaseline.setObjectName("btnBaseline")
        self.btnSingle = QtWidgets.QPushButton(self.centralwidget)
        self.btnSingle.setGeometry(QtCore.QRect(340, 620, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnSingle.setFont(font)
        self.btnSingle.setObjectName("btnSingle")
        self.pictureUtp = QtWidgets.QGraphicsView(self.centralwidget)
        self.pictureUtp.setGeometry(QtCore.QRect(1200, 110, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pictureUtp.setFont(font)
        self.pictureUtp.setObjectName("pictureUtp")

        # Load the image into a QPixmap
        script_dir = os.path.dirname(__file__)
        utp_path = os.path.join(script_dir, 'img/utp.jpg')
        pixmap = QPixmap(utp_path)
        if pixmap.isNull():
            print("Failed to load image")
        else:
            # Create a QGraphicsPixmapItem with the QPixmap
            pixmap_item = QGraphicsPixmapItem(pixmap)

            # Create a QGraphicsScene and add the QGraphicsPixmapItem to it
            scene = QGraphicsScene()
            scene.addItem(pixmap_item)

            # Set the QGraphicsScene as the scene for the QGraphicsView
            self.pictureUtp.setScene(scene)

        self.pictureFie = QtWidgets.QGraphicsView(self.centralwidget)
        self.pictureFie.setGeometry(QtCore.QRect(1200, 260, 120, 120))
        self.pictureFie.setObjectName("pictureFie")
        # Load the image into a QPixmap
        script_dir = os.path.dirname(__file__)
        fie_path = os.path.join(script_dir, 'img/fie.jpg')
        pixmap = QPixmap(fie_path)
        if pixmap.isNull():
            print("Failed to load image")
        else:
            # Create a QGraphicsPixmapItem with the QPixmap
            pixmap_item = QGraphicsPixmapItem(pixmap)

            # Create a QGraphicsScene and add the QGraphicsPixmapItem to it
            scene = QGraphicsScene()
            scene.addItem(pixmap_item)

            # Set the QGraphicsScene as the scene for the QGraphicsView
            self.pictureFie.setScene(scene)
        # self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        # self.graphicsView.setGeometry(QtCore.QRect(200, 110, 941, 491))
        # self.graphicsView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.graphicsView.setFrameShadow(QtWidgets.QFrame.Sunken)
        # self.graphicsView.setLineWidth(1)
        # self.graphicsView.setObjectName("graphicsView")

        # Crear un widget para la gráfica
        self.graphWidget = pg.PlotWidget(self.centralwidget)
        self.graphWidget.setXRange(350, 750, padding=0)
        self.graphWidget.setAutoFillBackground(True)
        self.graphWidget.setBackgroundBrush(QtCore.Qt.white)
        self.graphWidget.showGrid(x=True, y=True, alpha=0.3)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphWidget.setForegroundBrush(brush)

        self.graphWidget.setGeometry(QtCore.QRect(200, 110, 941, 491))
        self.graphWidget.setObjectName("graphWidget")
        self.graphWidget.setBackground("k" if "dark" == "dark" else "w")


        self.pictureIndicasat = QtWidgets.QGraphicsView(self.centralwidget)
        self.pictureIndicasat.setGeometry(QtCore.QRect(1200, 420, 120, 120))
        self.pictureIndicasat.setObjectName("pictureIndicasat")
        # Load the image into a QPixmap
        script_dir = os.path.dirname(__file__)
        indicasat_path = os.path.join(script_dir, 'img/indicasat.jpeg')
        pixmap = QPixmap(indicasat_path)
        if pixmap.isNull():
            print("Failed to load image")
        else:
            pixmap = pixmap.scaled(100, 100, QtCore.Qt.KeepAspectRatio)

            # Create a QGraphicsPixmapItem with the QPixmap
            pixmap_item = QGraphicsPixmapItem(pixmap)

            # Create a QGraphicsScene and add the QGraphicsPixmapItem to it
            scene = QGraphicsScene()
            scene.addItem(pixmap_item)

            # Set the QGraphicsScene as the scene for the QGraphicsView
            self.pictureIndicasat.setScene(scene)
        self.btnContinuous = QtWidgets.QPushButton(self.centralwidget)
        self.btnContinuous.setGeometry(QtCore.QRect(480, 620, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnContinuous.setFont(font)
        self.btnContinuous.setObjectName("btnContinuous")
        self.btnSaveData = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveData.setGeometry(QtCore.QRect(620, 620, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnSaveData.setFont(font)
        self.btnSaveData.setObjectName("btnSaveData")
        self.btnSettings = QtWidgets.QPushButton(self.centralwidget)
        self.btnSettings.setGeometry(QtCore.QRect(760, 620, 120, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnSettings.setFont(font)
        self.btnSettings.setObjectName("btnSettings")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(210, 10, 921, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(910, 620, 241, 41))
        self.progressBar.setProperty("value", 0)
        #self.progressBar.setMaximum(100)
        
        self.progressBar.setObjectName("progressBar")

        self.horaLabel = QtWidgets.QLabel(self.centralwidget)
        self.horaLabel.setGeometry(QtCore.QRect(1160, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.horaLabel.setFont(font)
        self.horaLabel.setObjectName("horaLabel")
        self.graphValuesLabel = QtWidgets.QLabel(self.centralwidget)
        self.graphValuesLabel.setGeometry(QtCore.QRect(10, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.graphValuesLabel.setFont(font)
        self.graphValuesLabel.setObjectName("graphValuesLabel")
        self.maxDBLabel = QtWidgets.QLabel(self.centralwidget)
        self.maxDBLabel.setGeometry(QtCore.QRect(10, 110, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.maxDBLabel.setFont(font)
        self.maxDBLabel.setObjectName("maxDBLabel")
        self.maxNMLabel = QtWidgets.QLabel(self.centralwidget)
        self.maxNMLabel.setGeometry(QtCore.QRect(10, 150, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.maxNMLabel.setFont(font)
        self.maxNMLabel.setObjectName("maxNMLabel")
        self.minDBLabel = QtWidgets.QLabel(self.centralwidget)
        self.minDBLabel.setGeometry(QtCore.QRect(10, 190, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.minDBLabel.setFont(font)
        self.minDBLabel.setObjectName("minDBLabel")
        self.minNMLabel = QtWidgets.QLabel(self.centralwidget)
        self.minNMLabel.setGeometry(QtCore.QRect(10, 230, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.minNMLabel.setFont(font)
        self.minNMLabel.setObjectName("minNMLabel")
        self.specificLabel = QtWidgets.QLabel(self.centralwidget)
        self.specificLabel.setGeometry(QtCore.QRect(10, 290, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.specificLabel.setFont(font)
        self.specificLabel.setObjectName("specificLabel")
        self.db435Label = QtWidgets.QLabel(self.centralwidget)
        self.db435Label.setGeometry(QtCore.QRect(10, 330, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.db435Label.setFont(font)
        self.db435Label.setObjectName("db435Label")
        self.db450Label = QtWidgets.QLabel(self.centralwidget)
        self.db450Label.setGeometry(QtCore.QRect(10, 370, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.db450Label.setFont(font)
        self.db450Label.setObjectName("db450Label")
        self.db500Label = QtWidgets.QLabel(self.centralwidget)
        self.db500Label.setGeometry(QtCore.QRect(10, 410, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.db500Label.setFont(font)
        self.db500Label.setObjectName("db500Label")
        self.db550Label = QtWidgets.QLabel(self.centralwidget)
        self.db550Label.setGeometry(QtCore.QRect(10, 450, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.db550Label.setFont(font)
        self.db550Label.setObjectName("db550Label")
        self.db570Label = QtWidgets.QLabel(self.centralwidget)
        self.db570Label.setGeometry(QtCore.QRect(10, 490, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.db570Label.setFont(font)
        self.db570Label.setObjectName("db570Label")
        self.db600Label = QtWidgets.QLabel(self.centralwidget)
        self.db600Label.setGeometry(QtCore.QRect(10, 530, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.db600Label.setFont(font)
        self.db600Label.setObjectName("db600Label")
        self.db650Label = QtWidgets.QLabel(self.centralwidget)
        self.db650Label.setGeometry(QtCore.QRect(10, 570, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.db650Label.setFont(font)
        self.db650Label.setObjectName("db650Label")
        self.longitudLabel = QtWidgets.QLabel(self.centralwidget)
        self.longitudLabel.setGeometry(QtCore.QRect(1200, 550, 111, 16))
        self.longitudLabel.setObjectName("longitudLabel")
        self.longitudBox = QtWidgets.QTextEdit(self.centralwidget)
        self.longitudBox.setGeometry(QtCore.QRect(1200, 570, 104, 31))
        self.longitudBox.setObjectName("longitudBox")
        self.absorcionLabel = QtWidgets.QLabel(self.centralwidget)
        self.absorcionLabel.setGeometry(QtCore.QRect(1200, 610, 111, 16))
        self.absorcionLabel.setObjectName("absorcionLabel")
        self.absorcionBox = QtWidgets.QTextEdit(self.centralwidget)
        self.absorcionBox.setGeometry(QtCore.QRect(1200, 630, 104, 31))
        self.absorcionBox.setObjectName("absorcionBox")
        self.messageBox = QtWidgets.QLineEdit(self.centralwidget)
        self.messageBox.setGeometry(QtCore.QRect(200, 69, 941, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.messageBox.setFont(font)
        self.messageBox.setAlignment(QtCore.Qt.AlignCenter)
        self.messageBox.setReadOnly(True)
        self.messageBox.setObjectName("messageBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 20))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnBaseline.setText(_translate("MainWindow", "Baseline"))
        self.btnSingle.setText(_translate("MainWindow", "Single"))
        self.btnContinuous.setText(_translate("MainWindow", "Continuous"))
        self.btnSaveData.setText(_translate("MainWindow", "Save Data"))
        self.btnSettings.setText(_translate("MainWindow", "Settings"))
        self.titleLabel.setText(_translate("MainWindow", "Universidad Técnológica de Panamá - Espectofotómetro - Muestras Covid-19 "))
        self.horaLabel.setText(_translate("MainWindow", "2023-11-06 14:52"))
        self.graphValuesLabel.setText(_translate("MainWindow", "Graph Values"))
        self.maxDBLabel.setText(_translate("MainWindow", "Máx dB: 0.00"))
        self.maxNMLabel.setText(_translate("MainWindow", "Máx nm: 0.00"))
        self.minDBLabel.setText(_translate("MainWindow", "Min dB: 0.00"))
        self.minNMLabel.setText(_translate("MainWindow", "Min nm: 0.00"))
        self.specificLabel.setText(_translate("MainWindow", "Specific Values:"))
        self.db435Label.setText(_translate("MainWindow", "dB 435nm: 0.00"))
        self.db450Label.setText(_translate("MainWindow", "dB 450nm: 0.00"))
        self.db500Label.setText(_translate("MainWindow", "dB 500nm: 0.00"))
        self.db550Label.setText(_translate("MainWindow", "dB 550nm: 0.00"))
        self.db570Label.setText(_translate("MainWindow", "dB 570nm: 0.00"))
        self.db600Label.setText(_translate("MainWindow", "dB 600nm: 0.00"))
        self.db650Label.setText(_translate("MainWindow", "dB 650nm: 0.00"))
        self.longitudLabel.setText(_translate("MainWindow", "Longitud de Onda:"))
        self.longitudBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">0.00 nm</span></p></body></html>"))
        self.absorcionLabel.setText(_translate("MainWindow", "Absorción:"))
        self.absorcionBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">0.00 dB</span></p></body></html>"))
        self.messageBox.setText(_translate("MainWindow", "Please press Single to start measuring..."))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
