# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
from PyQt5.QtGui import QPixmap

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 483)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 410, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 410, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(620, 70, 151, 131))
        self.graphicsView.setObjectName("graphicsView")

        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(625, 240, 141, 131))
        self.graphicsView_2.setObjectName("graphicsView_2")

        # self.graphicsView_3 = QtWidgets.QGraphicsView(self.centralwidget)
        # self.graphicsView_3.setGeometry(QtCore.QRect(10, 10, 591, 391))
        # self.graphicsView_3.setObjectName("graphicsView_3")

        # Crear un widget para la gráfica
        self.graphWidget = pg.PlotWidget(self.centralwidget)
        self.graphWidget.setXRange(420, 750, padding=0)
        # graphWidget.setYRange(-0.1, 2.1, padding=0)
        self.graphWidget.setAutoFillBackground(True)
        self.graphWidget.setBackgroundBrush(QtCore.Qt.white)
        self.graphWidget.showGrid(x=True, y=True, alpha=0.3)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphWidget.setForegroundBrush(brush)

        self.graphWidget.setGeometry(QtCore.QRect(10, 10, 591, 391))
        self.graphWidget.setObjectName("graphWidget")
        self.graphWidget.setBackground("k" if "dark" == "dark" else "w")
   


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
